### ISSUE TITLE
dyld: Library not loaded: @rpath/liblldb.6.0.0.dylib

### ISSUE THREAD

**Issue by geekonion** [abit-me/lldb.ios#1]
请问这个该怎么处理啊？
6s iOS 11.2.5
dyld: Library not loaded: @rpath/liblldb.6.0.0.dylib
  Referenced from: /usr/bin/lldb
  Reason: no suitable image found.  Did find:
	/usr/bin/../lib/liblldb.6.0.0.dylib: code signing blocked mmap() of '/usr/bin/../lib/liblldb.6.0.0.dylib'
	/usr/lib/liblldb.6.0.0.dylib: code signing blocked mmap() of '/usr/lib/liblldb.6.0.0.dylib'
Abort trap: 6

iOS 9.0.2是正常的。

**Comment by Inc0n** [comment]
有用
```
<key>get-task-allow</key>
<true/>
```
sign 过吗

我也有这问题

**Comment by abit-me** [comment]
用了那个参数，看日志是liblldb.dylib签名出错了，我没有iOS11.2.5的设备，下周一把签名脚本发给你帮我试试哈

**Comment by Inc0n** [comment]
lldb 在 iOS 上不知会有多方便，先行谢过了 🙏

**Comment by abit-me** [comment]
1. script:

#!/bin/bash
codesign -fs "lldb_codesign" lldb_package/usr/bin/lldb
codesign -fs "lldb_codesign" lldb_package/usr/bin/lldb-argdumper
codesign -fs "lldb_codesign" lldb_package/usr/lib/liblldb.6.0.0.dylib
codesign -fs "lldb_codesign" --entitlements debugserver-entitlements.plist lldb_package/usr/bin/debugserver

2. debugserver-entitlements.plist 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.springboard.debugapplications</key>
	<true/>
	<key>com.apple.springboard.launchapplications</key>
	<string></string>
	<key>com.apple.backboardd.launchapplications</key>
	<true/>
	<key>com.apple.backboardd.debugapplications</key>
	<true/>
	<key>com.apple.frontboard.launchapplications</key>
	<true/>
	<key>com.apple.frontboard.debugapplications</key>
	<true/>
	<key>com.apple.diagnosticd.diagnostic</key>
	<true/>
	<key>com.apple.security.network.server</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>get-task-allow</key>
	<true/>
	<key>task_for_pid-allow</key>
	<true/>
	<key>run-unsigned-code</key>
	<true/>
	<key>proc_info-allow</key>
	<true/>
	<key>platform-application</key>
	<true/>
	<key>seatbelt-profiles</key>
	<array>
		<string>debugserver</string>
	</array>
	<key>com.apple.backboard.client</key>
	<true/>
	<key>com.apple.bulletinboard.serverconduit</key>
	<true/>
	<key>com.apple.bulletinboard.utilities</key>
	<true/>
</dict>
</plist>


3. lldb_codesign cert(llvm/tools/lldb/docs/code-signing.txt)
On MacOSX lldb needs to be code signed. The Debug, DebugClang and Release 
builds  are set to code sign using a code signing certificate named 
"lldb_codesign". 

If you have re-installed a new OS, please delete all old lldb_codesign items
from your keychain. There will be a code signing certification and a public
and private key. Reboot after deleting them. You will also need to delete and
build folders that contained old signed items. The darwin kernel will cache 
code signing using the executable's file system node, so you will need to
delete the file so the kernel clears its cache.

If you don't have one yet you will need to:
- Launch /Applications/Utilities/Keychain Access.app

- In Keychain Access select the "login" keychain in the "Keychains"
  list in the upper left hand corner of the window.

- Select the following menu item:

	Keychain Access->Certificate Assistant->Create a Certificate...

- Set the following settings

	Name = lldb_codesign
	Identity Type = Self Signed Root
	Certificate Type = Code Signing

- Click Create
- Click Continue
- Click Done
- Click on the "My Certificates"
- Double click on your new lldb_codesign certificate
- Turn down the "Trust" disclosure triangle, scroll to the "Code Signing" trust
  pulldown menu and select "Always Trust" and authenticate as needed using your
  username and password.
- Drag the new "lldb_codesign" code signing certificate (not the public or private
  keys of the same name) from the "login" keychain to the "System" keychain in the 
  Keychains pane on the left hand side of the main Keychain Access window. This will
  move this certificate to the "System" keychain. You'll have to authorize a few
  more times, set it to be "Always trusted" when asked.
- Remove "~/Desktop/lldb_codesign.cer" file on your desktop if there is one.
- In the Keychain Access GUI, click and drag "lldb_codesign" in the "System" keychain
  onto the desktop. The drag will create a "~/Desktop/lldb_codesign.cer" file used in
  the next step.
- Switch to Terminal, and run the following:

sudo security add-trust -d -r trustRoot -p basic -p codeSign -k /Library/Keychains/System.keychain ~/Desktop/lldb_codesign.cer
rm -f ~/Desktop/lldb_codesign.cer

- Drag the "lldb_codesign" certificate from the "System" keychain back into the
  "login" keychain
- Quit Keychain Access
- Reboot
- Clean by removing all previously creating code signed binaries and rebuild
  lldb and you should be able to debug.

When you build your LLDB for the first time, the Xcode GUI will prompt you for permission
to use the "lldb_codesign" keychain. Be sure to click "Always Allow" on your first
build. From here on out, the "lldb_codesign" will be trusted and you can build from the
command line without having to authorize. Also the first time you debug using a LLDB that
was built with this code signing certificate, you will need to authenticate once.

**Comment by geekonion** [comment]
我把安装的文件重签名了还是一样的错误，求帮助。
![default](https://user-images.githubusercontent.com/12871217/43441920-f0b288e0-94ce-11e8-8f04-f90979cbfbbd.png)

**Comment by geekonion** [comment]
暂时解决了，签名的问题，我把lldb及依赖的dylib都用企业证书签名了，就可以了。我越狱没开tweak，应该是AppSync不生效，自签名的也有问题。还是个逆向新手，签名这方面没玩六。简单敲了几个命令，暂时没发现问题。哪位若有更好的方案，望赐教。
求个知识呗，lldb for iOS是怎么编译出来的。

**Comment by geekonion** [comment]
发现有问题，attach上以后，c会崩溃。这个应该是debugserver的坑。
<img width="753" alt="default" src="https://user-images.githubusercontent.com/12871217/43571500-afc02a2a-966f-11e8-8c21-5c2f6905fa2a.png">

**Comment by abit-me** [comment]
编译很棘手，所以没有开源。debugserver你签名了吗？

**Comment by geekonion** [comment]
签了，debugserver是可以启动的，调试自己的应用都没问题。
想学习个思路，求分享。

**Comment by abit-me** [comment]
有这些知识点：
1.交叉编译，我使用的是cmake 和 ninja
2.设置CMakefile文件，主要是一些宏的设置
3.缺头文件，这时候把macOS用的头文件拷贝到iOS开发目录下
4.iOS上有个local_thread不支持，备注掉即可
5.签名，用的是lldb_codesign自签名证书
6.dpkg 打包

**Comment by geekonion** [comment]
好的，非常感谢

**Comment by Inc0n** [comment]
我的 lldb source 是从 https://github.com/llvm-mirror/lldb 下载下来的，
你们也是同样的 source 吗

**Comment by abit-me** [comment]
对！但建议用release 6.0版本

**Comment by Inc0n** [comment]
compile 时经常遇到头文件找不到
```
../tools/darwin-debug/darwin-debug.cpp:27:10: fatal error: 'crt_externs.h' file not found
#include <crt_externs.h> // for _NSGetEnviron()
```
可是到 /usr/include 里面全部都有，在CMakeList.text 里面加了`include_directories(/usr/include/)`也不行，请问你是怎么解决的？

**Comment by Inc0n** [comment]
解决了

> 3.缺头文件，这时候把macOS用的头文件拷贝到iOS开发目录下

慢慢 cp 各个头文件到 include 文件夹里

**Comment by Inc0n** [comment]
但是这个我是真的需要些指点   

```
../source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp:3056:44: error: 'SetFile' is a protected member of 'lldb_private::FileSpec'
                                    so_dir.SetFile(
                                    ~~~~~~~^~~~~~~
../include/lldb/Utility/FileSpec.h:570:8: note: declared protected here
  void SetFile(llvm::StringRef path, bool resolve_path);
```
