### ISSUE TITLE
could you plz share knowledge

### ISSUE THREAD

**Issue by Inc0n** [abit-me/lldb.ios#2]
can you please share how you would compile this into working for iOS 

Thanks !! :)

**Comment by abit-me** [comment]
OK. I will share you the build script nest Monday

**Comment by Inc0n** [comment]
that would be very helpful thank you very much

**Comment by abit-me** [comment]
Building lldb.ios is difficult, You may need many other works, here is the script, but it not enough, If you are really interesting to build it(It may cost a lot of time, and it is the reason why I don't want open source it),You can register a gitee.com I will share my code int it to you.

#!/bin/bash
cmake -G "Ninja" \
	-DCMAKE_CROSSCOMPILING=1 \
	-DCMAKE_OSX_ARCHITECTURES="armv7;arm64" \
	-DCMAKE_TOOLCHAIN_FILE=../llvm/cmake/platforms/iOS.cmake \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_BUILD_RUNTIME=Off \
	-DLLVM_INCLUDE_TESTS=Off \
	-DLLVM_INCLUDE_EXAMPLES=Off \
	-DLLVM_ENABLE_BACKTRACES=Off \
	-DHAVE_FUTIMENS=0 \
	-DCLANG_INCLUDE_TESTS=Off \
	-DLLDB_INCLUDE_TESTS=Off \
	-DLLDB_DISABLE_PYTHON=1 \
	../llvm
