### ISSUE TITLE
Need helping building for a Cydia/APT repository.

### ISSUE THREAD

**Issue by MCApollo** [abit-me/lldb.ios#3]
I already have compiled Python 3.6.4 for aarch64 on iOS and was wondering how the source of lldb 6.0 was built.

CMake stops me at not having libatomic, is there something I’m missing? My build-host is a Ubuntu machine.

**Comment by abit-me** [comment]
I have encounter lots of problem too when i build lldb.ios, My solution:
1. Make sure if there is alternatives libs（check out the macro in the source）
2.if there has no alternatives，make sure if you can find out some lib have the same function
3.Else if write the code by yourself
4.otool -L python2.7 for iOS（someone have builded it）check out if there has the libautomatic
5.I can share with you the build script of lldb.ios at Monday

**Comment by MCApollo** [comment]
Thank you. 
I’ll be needy and wait for that build script; I checked python 2.7, libatomic wasn’t linked at compile time. I have a feeling that I’m just missing something or I left something out of my cmake toolchain file.

**Comment by abit-me** [comment]
here is my script, If you want to use it to build lldb.ios, You need many other works

#!/bin/bash
cmake -G "Ninja" \
	-DCMAKE_CROSSCOMPILING=1 \
	-DCMAKE_OSX_ARCHITECTURES="armv7;arm64" \
	-DCMAKE_TOOLCHAIN_FILE=../llvm/cmake/platforms/iOS.cmake \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_BUILD_RUNTIME=Off \
	-DLLVM_INCLUDE_TESTS=Off \
	-DLLVM_INCLUDE_EXAMPLES=Off \
	-DLLVM_ENABLE_BACKTRACES=Off \
	-DHAVE_FUTIMENS=0 \
	-DCLANG_INCLUDE_TESTS=Off \
	-DLLDB_INCLUDE_TESTS=Off \
	-DLLDB_DISABLE_PYTHON=1 \
	../llvm
